### ISSUE TITLE
midterm finished

### ISSUE THREAD

**Issue by assrichiacoli** [assrichiacoli/hw#10]

**Comment by YakutovDmitriy** [comment]
* `subpalindrome` - ok
* `pascals` - ok
* `spiral` - ok
* `fibonacci` - ok
* `brackets2` - ne ok :(. This functions should generate values. Now it returns `list`

**Comment by assrichiacoli** [comment]
done

**Comment by YakutovDmitriy** [comment]
It is much more complicated than it can be, but ok
