### ISSUE TITLE
8

### ISSUE THREAD

**Issue by assrichiacoli** [assrichiacoli/hw#11]

**Comment by YakutovDmitriy** [comment]
Hello, I'm sorry for late answer.
Where is your `LinkedQueue`? You and Daria must be tripping

**Comment by assrichiacoli** [comment]
added it)

**Comment by YakutovDmitriy** [comment]
Did you try to test it? Some of your methods get `AttributeError`

**Comment by assrichiacoli** [comment]
I decided to change names last minute and didn't test(

**Comment by YakutovDmitriy** [comment]
Still the same. What is `value`?

**Comment by assrichiacoli** [comment]
value is something I forgot to rename too))) I know how it looks like, but I do not just copy thoughtlessly, everything I send I understand

**Comment by YakutovDmitriy** [comment]
Ok, it works, good

I believe you understand what are you doing. But I want you to carefully tests everything you send to me, so I am upset a bit :(
