### ISSUE TITLE
Exam task for Tatiana Volkova

### ISSUE THREAD

**Issue by YakutovDmitriy** [assrichiacoli/hw#14]
#### Main requirements

Your program should never fail.

You are free to implement the task as you want. In particular, if there are some uncertainties, you have to decide what to do.

You are free to add some functionality. Please describe all features you added.

#### Implement application `avia.py` to work with avia tickets.

You should store information about flights in file [flights.av](https://gist.github.com/YakutovDmitriy/fcb2e505da94ed308e0e95836a76f685).

Each item has several properties:
  * From - departure airport
  * To - destination airport
  * Departure - time of departure
  * Arrival - time of arrival
  * Cost - cost of flight ticket in dollars
  * Airlines - air company that operates the flight

You can assume that:
  * All time properties have the same timezone
  * All flights are shorter than one day
  * Each flight happens every day

Note that:
  * Some flights span across two days (in this cast `Departure > Arrival`)

Passengers can travel from one airport to another with transfers. But our service will provide an opportunity to make at most one transfer:

  * It is impossible to make a transfer to a flight such that its departure is earlier than first flight's departure plus 40 minutes
  * It is possible to make second flight at the next day after the first one:
      ```
      Moscow     15:20  ->  Frankfurt  19:00  
      Frankfurt  00:40  ->  New-York   09:50  (the next day)
      ```

---

* Add: `python avia.py add <From> <To> <Departure> <Arrival> <Cost> <Airlines>`

    Command should add a new flight with the given properties.

* Find: `python avia.py top <From> <To> [<N>]`

    Command should find best ways from `<From>` airport to `<To>` airport for a passenger. Here are the rules how to know if one way (`way-1`) is better than (`way-2`):

    * `way-1` has less number of transfers from one airlines company to another than `way-2` (rule #1)
    * `way-1` has less total number of transfers than `way-2` (rule #2)
    * `way-1` is faster than `way-2` (rule #3)
    * `way-1` is cheaper than `way-2` (rule #4)

    Rules are listed in order from the strongest to the weakest, compare two ways by the first matching rule in this list.

    Optional argument `<N>` is number of shown ways. If this argument is absent, show one way - the best way.

    List of ways should be ordered from the best one to the worst one. Print it in some pretty way, for example:

      Tokyo-NRT             ->  New-York-JFK   $1100
      Tokyo-NRT      03:40  ->  Frankfurt-FRA  16:00
      Frankfurt-FRA  00:40  ->  New-York-JFK   09:50  (the next day)

* Find cheap: `python avia.py find-cheap <From> <To> [<N>]`

    Command should do the same as the previous one, but with new order of rules:

    * rule #4 - cheap ways
    * rule #1 - number of airlines change
    * rule #2 - total number of transfers
    * rule #3 - time of travel

    Here the cheapest way is the best one.

**Comment by assrichiacoli** [comment]
I really tried, like 20-hours-non-stop tried (not kidding), u menya uzhe malchiki krovavie v glazax, but either the task is too complicated or I am too dumb, most likely both :(
`add` works, but one digit hours has to have one additional space before the hours (like 1:20 6:40 etc) in order for `top` and `find-cheap` to work further, i didn't have time to solve this problem
`top` and `find-cheap` kinda work, not really for 2-transfer flights, and outputs are not that pretty
also, if it does not work at all, tell me, it does but it depends on where the newlines in the file are located
and the code itself is hideous, I am sorry

**Comment by YakutovDmitriy** [comment]
Actually your task is one of the hardest tasks. I hoped you would handle this.

Your program is almost work. The only issue I found:
* In file `flights.av` there is only one EOF (end-of-line) at the end of the file. But your implementation requires two EOF-s. After I added a new one it worked.
* This is not an issue, but. You chose bad way to store all information. You could create class `Flight` and store all information here, it would be much easier to do it. Here is an example of good implementation (it is easier task with implementation of taxi-service, but I guess you'll got an idea):
https://github.com/romanovamar/bio-python/blob/master/taxi.py

You got 9 points

**Comment by assrichiacoli** [comment]
yeah, I started with classes first but I am still not too good with them and the time was too limited (for me) so I chose an awful but safe way (still failed though lmao))))

**Comment by YakutovDmitriy** [comment]
I still recomment you to read some from the link :)

**Comment by assrichiacoli** [comment]
I intended to remake it properly on the winter break so I will !

**Comment by YakutovDmitriy** [comment]
Ok, send the result to me, I'll read it and make some feedback)

**Comment by assrichiacoli** [comment]
oh ok thanks!! good luck on your exams

**Comment by YakutovDmitriy** [comment]
Actually I'm going to otchislit'sya from the university, so I'm not going to pass my exams, but thank you))

**Comment by assrichiacoli** [comment]
so you will not attend classes with us?:( well then good luck with whatever you are going to do with your life)

**Comment by YakutovDmitriy** [comment]
Actually yes, I won't teach you how to do other cool stuff in python :( But there are other reasons, we've discussed about them on one of the last classes. The main one is that I have no research experience in python, only development experience.

**Comment by assrichiacoli** [comment]
yeah I know! I meant attending like learning with us probably, you mentioned it last time

**Comment by YakutovDmitriy** [comment]
Oh, in this terms I still can attend on your classes
I won't be a university student but I'll still university staff member)

**Comment by assrichiacoli** [comment]
👍
