### ISSUE TITLE
task1 rewritten

### ISSUE THREAD

**Issue by assrichiacoli** [assrichiacoli/hw#4]
эссерт и пеп8

**Comment by YakutovDmitriy** [comment]
There are two problems:
* You have a type in your file, so I can't execute it
* You have to write test in the following way:
  * When you execute your file, tests should be executed
  * When you import your file from other file, tests should not be executed. Now your tests will be executed while importing

Please fix these 2 issues

**Comment by assrichiacoli** [comment]
a type - you mean a typo?
done

**Comment by YakutovDmitriy** [comment]
Yeah, I have a typo in word "typo" :)

**Comment by YakutovDmitriy** [comment]
Almost good. There is one warning in pep

**Comment by assrichiacoli** [comment]
I actually don't have any...

**Comment by YakutovDmitriy** [comment]
My pep:
`task1rewritten.py:51:1: W391 blank line at end of file`
Ok, lets say it is ok

Please do not use spaces and other strange symbols except letters, digits or underscores in name of python file. It becomes impossible for importing
