### ISSUE TITLE
task 3

### ISSUE THREAD

**Issue by assrichiacoli** [assrichiacoli/hw#5]
do I have to test my implementations with all the tests? I am not sure how to do that in this task, also some of them are infinite

**Comment by YakutovDmitriy** [comment]
* It is not necessary to create tests for this task. But you can test functions by taking `next` several times
* You have implemented `filter` by yourself, it is not necessary, python has built-in function `filter` with the same meaning
* `repeatntimes` do something strange. Test it with test where `elems` is not list or tuple ot string (e.g, `elems = range(5)`)
* Please test `digitsumdiv`, it contains a mistake
* `productif` contains more than one line of code
* Other functions are ok

**Comment by assrichiacoli** [comment]
oh, at some point it told me that it doesn't understand what filter is🤔
done
in productif at first I did kinda the same but filter instead of map, it didn't work. Is it because map returns iterable with elements that can be multiplied and filter returns list of tuples that cannot???

**Comment by YakutovDmitriy** [comment]
I can't see any commits related to hw-3. Did you push them?

**Comment by assrichiacoli** [comment]
ой)0 
I did now

**Comment by YakutovDmitriy** [comment]
* `repeatntimes`. You are trying to construct a list from iterable. But this iterable can contain infinite number of elements. In such case you are trying to create infinite list. It takes infinite time and memory for doing this. Try to avoid using additional memory. You can read `itertools` docs for hints.
Also you are yielding only one element &mdash; list with result. But you have to yield several elemens. E.g. `list(repeatntimes([1, 2], 3)) = [[1, 2, 1, 2, 1, 2]]` but should be `[1, 2, 1, 2, 1, 2]`
* `digitsumdiv` is ok
* `productif` is almost good. You have `TypeError` on some special tests

**Comment by assrichiacoli** [comment]
done

so, do I understand correctly we use map and not filter (in this particular case in productif), because filter returns something like this [(),()...] so we cannot multiply tuples and map returns something like this [1,2,3...]? 

also in repeatntimes, itertools.repeat returns n iterators and we yield elements from each one 1 time? so the result is one large iterator (combined from n small iterators)?

also 1,2,3 or range are iterators and can be yielded (once) creating new iterator, and [1,2,3] is iterable and when we yield from it (only once too?) it creates iterator too? 
the functions that create iterators are generators and it doesn't matter what they create them from?

I am a little bit lost(

**Comment by YakutovDmitriy** [comment]
Everything is ok!
I'll close the issue. If you want to continue discussion lets move it to telegram
