### ISSUE TITLE
))

### ISSUE THREAD

**Issue by assrichiacoli** [assrichiacoli/hw#9]

**Comment by YakutovDmitriy** [comment]
* `valuesunion`: Try this: `valuesunion({1: 5}, {1: 10})`
* `popcount` ok
* `powers` ok
* `isIPv4`. My solutions says that `192.168.01.41` is incorrect IP-address, but yours returns opposite verdict. It is contentious issue is this IP correct or not. Lets accept both opinions. Ok

**Comment by YakutovDmitriy** [comment]
Also your file had no extension `.py` :(

**Comment by assrichiacoli** [comment]
so itertools.chain.from_iterable replaces value if the key is the same?
i was in a rush(

**Comment by YakutovDmitriy** [comment]
The problem is in `dict`. `dict` can't store more than one value associated with single key. So the result dict lost one of the values. Now it is ok
